packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@vercel/speed-insights'

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
